name = "TestRegistry"
uuid = "d09a6c28-d263-11e9-1d76-7b9f7015dbd4"
repo = "https://github.com/JuliaComputing/TestRegistry.git"

description = """
JC Test Registry
"""

[packages]
009559a3-9522-5dbb-924b-0b6ed2b22bb9 = { name = "XGBoost", path = "X/XGBoost" }
7876af07-990d-54b4-ab0e-23690620f79a = { name = "Example", path = "E/Example" }
