name = "TestRegistry"
uuid = "d09a6c28-d263-11e9-1d76-7b9f7015dbd4"
repo = "https://github.com/JuliaComputing/TestRegistry.git"

description = """
JC Test Registry
"""

[packages]
7876af07-991d-54b4-ab0e-23690620f79b = { name = "PrivateExample", path = "P/PrivateExample" }
aa32b3ae-9d2b-4028-8f83-f09b732ffa1f = { name = "TestDependency", path = "T/TestDependency" }
c21cdcaf-0d93-4d92-8cdb-99636d8a79d4 = { name = "SampleDash", path = "S/SampleDash" }
cb761652-754a-11e9-1d2d-6dcc2b16127a = { name = "AnotherTest", path = "A/AnotherTest" }
f269a46b-ccf7-5d73-abea-4c690281aa53 = { name = "TimeZones", path = "T/TimeZones" }
f51c398c-f501-11e9-1bf8-2302628c9e2e = { name = "LeucineModel", path = "L/LeucineModel" }
