name = "TestRegistry"
uuid = "d09a6c28-d263-11e9-1d76-7b9f7015dbd4"
repo = "https://github.com/JuliaComputing/TestRegistry.git"

description = """
JC Test Registry
"""

[packages]
7876af07-991d-54b4-ab0e-23690620f79b = { name = "PrivateExample", path = "P/PrivateExample" }
f269a46b-ccf7-5d73-abea-4c690281aa53 = { name = "TimeZones", path = "T/TimeZones" }
